### PR TITLE
Patches typo?

### PR DESCRIPTION
**Pull request by Slind14**
I think this is meant to be this way, which would explain why it isn't working.

### CODE REVIEW

**Comment by LunNova** [comment]
From looking at it, the documentation is incorrect but the code is right. I renamed some parameters to make more sense when extracting JavaPatcher from TT, and didn't update the log message `PatcherLog.warn("Must set methods to run on if using fieldClass.");`

The `fieldClass` attribute is used lower down at `String clazz = attributes.get("fieldClass");`.

The `classContainingField` attribute is the class the field is a member of. The `fieldClass` attribute is the type of the field. It's... not particularly clear.

How are you trying to use the patch?

**Comment by Slind14** [comment]
`<replaceFieldInitializer field="field_147483_b" fieldClass="net.mineyourmind.tweaks.collections.ListWithSet"/>`

**Comment by Slind14** [comment]
just came across this issue again as someone updated the custom version to the original. I still believe this is a mistake unless I'm doing the patch wrong. As the given patch works fine with the small adjustment of the if check.

**Comment by Slind14** [comment]
Hey @nallar ,
do you mind looking over this again? I still think its a bug as it only works with the change. I would love to use the latest modpatcher/tickprofiler without the need to manually update javapatcher to the custom version every time ;)

**Comment by LunNova** [comment]
You're right, I screwed that up. Sorry :/

**Comment by Slind14** [comment]
thanks :)

**Pull request merged**
